### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by qianwangthu** [coxlab/prednet#10]
I roll back to keras 1.0.7 but it doesn't work for this problem...

> Epoch 1/150
> Traceback (most recent call last):
>   File "kitti_train.py", line 75, in <module>
>     validation_data=val_generator, nb_val_samples=N_seq_val)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/training.py", line 1444, in fit_generator
>     class_weight=class_weight)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/training.py", line 1216, in train_on_batch
>     check_batch_dim=True)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/training.py", line 962, in _standardize_user_data
>     exception_prefix='model input')
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/training.py", line 108, in standardize_input_data
>     str(array.shape))
> Exception: Error when checking model input: expected input_1 to have shape (None, 10, 3, 128, 160) but got array with shape (4, 10, 128, 160, 3)
>

**Comment by qianwangthu** [comment]
Trying to fix it following https://github.com/coxlab/prednet/pull/5/files. Thx!

**Comment by bill-lotter** [comment]
Sorry about the delay in this, but I fixed it so that both dim_orderings work now.
