### ISSUE TITLE
the dropbox address for the processed data is no longer functional

### ISSUE THREAD

**Issue by flybirp** [coxlab/prednet#16]
please change to an address, thanks

**Comment by hello-world-zsp** [comment]
actually, I have downloaded the processed data by the provided address. 
But it is only 1.92 GB, and the X_train.hkl is broken when unzipped.
Could someone please check the processed data? Thanks a lot.

**Comment by bill-lotter** [comment]
I just tried it and it seems to be working and the X_train seems to be fine.  Can you show what errors you're getting?

**Comment by hello-world-zsp** [comment]
I have downloaded it again, everything is okay this time! thanks! 
should i cancel my comment?

**Comment by bill-lotter** [comment]
Okay cool!  No you can leave it, it's fine
