### ISSUE TITLE
Multiple Timesteps Prediction 

### ISSUE THREAD

**Issue by BadourAlBahar** [coxlab/prednet#17]
Can you please provide the code for multiple timesteps prediction as well as for the finetuned multiple timesteps prediction?

**Comment by bill-lotter** [comment]
Hello, to do multiple time step prediction, you just have to use the 'extrap_start_time' variable for the PredNet layer.  For instance, if you set 'nt' to 15 and 'extrap_start_time' to 10, then after 10 frames, it will make up to a 5 time step ahead prediction.
