### ISSUE TITLE
1 input -> next predicted output

### ISSUE THREAD

**Issue by yhj7522** [coxlab/prednet#24]
Hi

thank for your code

i want only predicted output which is predicted based on previous input sequence
not to compare actual and predicted output
to predict future situation just using present situation

how can i do this??

Thx.

**Comment by bill-lotter** [comment]
Hello, are you saying you just want to predict multiple steps ahead?

**Comment by lengoanhcat** [comment]
You can do that by feeding 'prediction' frame back as input frame in a loop of n steps. However, I don't think the prediction result will be accurate or sensible. 

Another way is trying to redesign prednet with a bigger memory so it can 'remember' and 'predict' more than 1 frame. It is just my speculation and inspiration for further work on prednet. 

Many thanks for inspiring paper and very useful codes !!!
