### ISSUE TITLE
about CalTech dataset

### ISSUE THREAD

**Issue by kikyou123** [coxlab/prednet#32]
When i using the CalTech Pedestrian dataset to test, I get the SSIM 0.93 that is higher than the paper got, I think it is because the frame rate is not match the KITTI dataset, so can you tell me what your process in the CalTech data, what is the frame rate?

**Comment by bill-lotter** [comment]
For CalTech, I downsample in time by a factor of two to make it match the frame rate of KITTI.  The only other processing is cropping and resizing to 128x160.

**Comment by kikyou123** [comment]
I notice that the CalTech frame rate is 30帧/sec，and the kitti frame rate is 10帧/sec。when I downsample in time by a factor of two i got the SSIM 0.90. i still can not understand why? can you release  the code that using the CalTech test? Thank you very much!!

**Comment by bill-lotter** [comment]
Sorry I meant downsample by factor of 3 (to match kitti frame rate - as mentioned in the paper)

**Comment by kikyou123** [comment]
ok, thank you very much! can I ask you what part of the dataset that you use? 
![image](https://user-images.githubusercontent.com/19486038/31699844-d2957880-b3f7-11e7-8f02-48a980af2970.png)
I use the set06-set10

**Comment by bill-lotter** [comment]
No problem.  I used sets 6-10, which is the test partition if I recall correctly.
