### ISSUE TITLE
Can the model predict other video frame without training just using the pretrained model?

### ISSUE THREAD

**Issue by guanfuchen** [coxlab/prednet#36]
I want to use the model to predict other video, should this model be trained for every different video, or just use one trained model to predict other videos?

**Comment by 17Skye17** [comment]
I am facing the same question, have you figured it out? : )

**Comment by bill-lotter** [comment]
Typically the model will perform best when the testing distribution reflects the training distribution, but there may be some degree of extrapolation if the testing samples share similar properties to training.
