### ISSUE TITLE
Custom Crop Size

### ISSUE THREAD

**Issue by alvinxiii** [coxlab/prednet#39]
How to change the image crop size? I'm having a problem when I change it to (480,size)

Code:
```
n_channels, im_height, im_width = (3, 480, 320)
input_shape = (n_channels, im_height, im_width) if K.image_data_format() == 'channels_first' else (im_height, im_width, n_channels)
print(input_shape)
stack_sizes = (n_channels, 48, 96, 192)

```
Error:
`ValueError: Error when checking input: expected input_1 to have shape (None, 10, 480, 320, 3) but got array with shape (4, 10, 128, 160, 3)`

**Comment by blanchardn13** [comment]
I believe the crop function is written specifically for the kitti data. It assumes that video or image width > height.

**Comment by PyPatel** [comment]
When training on a new dataset, the image size has to be divisible by 2^(nb of layers - 1) because of the cyclical 2x2 max-pooling and upsampling operations.

You have to add conv. layers to get the desires end output.
