### ISSUE TITLE
Custom Output Shape

### ISSUE THREAD

**Issue by mitkina** [coxlab/prednet#51]
Hello,

I was wondering if there's an easy way to change prednet output shape to be different than the input in the model itself? I am trying to input 128x128x3 images and output 128x128x1 images. I changed the appropriate data_utils functions, but not sure what the best way to do it within prednet.py is?

Thanks!
Masha

**Comment by matinhosseiny** [comment]
The input and output are the same sizes in formula 3 (Relu (A-Ahat)).  You can change the design by adding a one by one convolution for input to reduce the input dimension.

**Comment by mitkina** [comment]
This would be only in layer zero, correct?

**Comment by matinhosseiny** [comment]
yes

**Comment by mitkina** [comment]
Thank you!
