### ISSUE TITLE
Non-RGB Images

### ISSUE THREAD

**Issue by mitkina** [coxlab/prednet#52]
Hello,

Is there anything that needs to be changed to pass in images with channel size of 1 instead of 3 as in RGB within the model (besides setting n_channels)?

Thanks!

**Comment by matinhosseiny** [comment]
just change this line :
n_channels, im_height, im_width = (1, 64, 64)
in kitti_train.py

**Comment by mitkina** [comment]
Thanks! I realized I was having batch size/learning rate tuning issues!
