### ISSUE TITLE
What is the Copy last frame?

### ISSUE THREAD

**Issue by kimna4** [coxlab/prednet#57]
Hello,
First of all, thank you for publishing great study.

The question is that What is the “Copy-Last-Frame”?
I don’t know exactly how I can use this approach as a baseline.
Could you tell me about the “Copy-Last-Frame”?

**Comment by severin1992** [comment]
You compare the MSE of the following:
1.) Your t+1 prediction vs. the ground truth of t+1
2.) Ground truth of t+1 vs. ground truth of t

Here, 2.) is your baseline (copy last frame). The assumption is that my simplest prediction is just not changing anything. t+1 will exactly be like t. 
So, when your MSE of 1.) is lower than 2.) your model is actually better than your baseline. 
@kimna4
