### ISSUE TITLE
ValueError on images of size (1340,1388)

### ISSUE THREAD

**Issue by kegbo** [coxlab/prednet#59]
I have used prednet code to train models with images of sizes (128, 160) (280,400) and (1000,1000).   I have a new batch of images of size (1340,1388) which fail with the error below.  

"ValueError: Dimension 1 in both shapes must be equal, but are 335 and 334. Shape
s are [?,335,347] and [?,334,346]. for 'pred_net_1/concat_1' (op: 'ConcatV2') wi
th input shapes: [?,335,347,96], [?,335,347,192], [?,334,346,192], [] and with c
omputed input tensors: input[3] = <3>."

**Comment by ronykalfarisi** [comment]
Hi @kegbo , I'm trying to train a model with bigger image resolution but I got memory error even for 200x200 and I'm using RTX 2070 with 8GB. What is your GPU specs? Thanks

**Comment by yiminking** [comment]
@kegbo Your image size needs to be divisible by 2**(nb of layers - 1)
