### ISSUE TITLE
Problem with the file kitti_evaluate.py

### ISSUE THREAD

**Issue by Murchana** [coxlab/prednet#6]
I am using Windows 7, Anaconda2, python 2.7.12, Theano 0.9.0, keras 1.1.2.
I downloaded the processed data from the files: download_data.sh and download_files.sh. Then I am trying to run the kitti_evaluate.py file through Anaconda promt. The file runs, but no Result_data file is created and no plot is shown. I get this:
![untitled](https://cloud.githubusercontent.com/assets/24236639/20691636/d764a598-b597-11e6-8a76-9525035090ca.png)

I am very new to python, I don't understand what it means. I suspect it might be a problem of theano. Can anyone help??
Thanks in advance!!

**Comment by adamwtow** [comment]
I'm not sure where the file is located in Windows, but find the file keras.json and change the image_dim_ordering setting to "th" as opposed to "tf". That worked for me on Mac OS 10.12.2.

**Comment by bill-lotter** [comment]
Hi Murchana, sorry for the very long delay, but are you still having issues?  I can't see the full exception in the screen shot you posted, but if it had to do with the image_dim_ordering, it should work now with both.
