### ISSUE TITLE
problem in training

### ISSUE THREAD

**Issue by qianwangthu** [coxlab/prednet#7]
I'm using Ubuntu 14.04, cuda 7.5, cuDNN5 and tensorflow r0.11
When I try to run kitti_train.py it shows
![2016-12-04 7 31 49](https://cloud.githubusercontent.com/assets/9479736/20873055/b3f28e52-ba58-11e6-95e9-ae33c5771024.png)
It seems a bug?

**Comment by bill-lotter** [comment]
Hello,

At the moment, the code is only validated with theano.  Please try with that.
