### ISSUE TITLE
Tensorflow plans?

### ISSUE THREAD

**Issue by danbri** [coxlab/prednet#8]
What are the prospects of this running (someday) with TF backend? Any plans in that direction?

noting

https://github.com/coxlab/prednet/pull/5

https://github.com/coxlab/prednet/issues?utf8=✓&q=is%3Aissue%20tensorflow

**Comment by moliusimon** [comment]
Hello danbri, not the developer but have been testing this method on tensorflow (had an incompatible version of theano) and seems to work out of the box.

For it to work, configure keras to use "image_dim_ordering" = "th" and "backend" = "tensorflow".

**Comment by bill-lotter** [comment]
Hi danbri and moliusimon, sorry about the delay, but it should work for both backends and both image_dim_orderings now.
